// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBqFLiJTN_zIRCGqk_KlYpxXnKYo5U2L-M',
    appId: '1:748781621652:web:1763b8ce6d0929c654ff81',
    messagingSenderId: '748781621652',
    projectId: 'telalogin-f6199',
    authDomain: 'telalogin-f6199.firebaseapp.com',
    storageBucket: 'telalogin-f6199.appspot.com',
    measurementId: 'G-3V3LF6NSJ7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBnEbFvX9EcJ1vGj4IFgg81Z_qyAPVz_4E',
    appId: '1:748781621652:android:ddaddf989825564d54ff81',
    messagingSenderId: '748781621652',
    projectId: 'telalogin-f6199',
    storageBucket: 'telalogin-f6199.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA5j3m7niHgnsXhjGZqrmC9xsDRaAa47Gc',
    appId: '1:748781621652:ios:5d5d7c4a9c6416e754ff81',
    messagingSenderId: '748781621652',
    projectId: 'telalogin-f6199',
    storageBucket: 'telalogin-f6199.appspot.com',
    iosBundleId: 'com.example.responsividade',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA5j3m7niHgnsXhjGZqrmC9xsDRaAa47Gc',
    appId: '1:748781621652:ios:2daa9f4361e5e66554ff81',
    messagingSenderId: '748781621652',
    projectId: 'telalogin-f6199',
    storageBucket: 'telalogin-f6199.appspot.com',
    iosBundleId: 'com.example.responsividade.RunnerTests',
  );
}
